# Features enabled: Logs, CSM, Process, USM, CNM

registry: "public.ecr.aws/datadog"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  tags:
    - "env:staging"
  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true
  securityAgent:
    runtime:
      enabled: true
    compliance:
      enabled: true
  sbom:
    containerImage:
      enabled: true
    host:
      enabled: true
  processAgent:
    enabled: true
    processCollection: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
